service: serverless-money-expense-api

provider:
  name: aws
  runtime: go1.x
  region: ap-south-1
  stage: ${opt:stage}

functions:
  api:
    handler: bin/main
    events:
      - http:
          path: /
          method: GET
      - http:
          path: /getAllUsers
          method: GET
      - http:
          path: /health
          method: GET
package:
  patterns:
    - "!*/**"
    - bin/main
